version: '3.8'  # 3.8+ supports the `gpus:` directive

services:
  redis:
    image: redis:7.4.4

  web:
    build: .
    image: translateocr-web:gpu
    ports:
      - '8000:8000'
    gpus: all              # <-- give this service access to all GPUs
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    depends_on:
      - redis

  worker:
    build: .
    image: translateocr-worker:gpu
    command: celery -A app.tasks.tasks worker --loglevel=info
    gpus: all              # <-- GPU for your OCR tasks
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis

  flower:
    image: mher/flower
    ports:
      - '5555:5555'
    depends_on:
      - redis
