version: 1
disable_existing_loggers: false  # Allows other loggers to work alongside

formatters:
  default:
    format: "%(asctime)s %(levelname)s %(name)s [%(module)s:%(lineno)d] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    filename: app.log
    formatter: default

loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: false  # Prevents duplicate logs
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: WARNING  # Reduce access log noise
  app:
    handlers: [console, file]  # Log to both console and file
    level: DEBUG
    propagate: false

root:
  handlers: [console]
  level: INFO